### ISSUE TITLE
Game glitches out after trying to hire someone

### ISSUE THREAD

**Issue by Amir1460** [hovgaardgames/bigambitions#1001]
### Build number

606

### Bug description

Hiring a person removes my whole HUD and locks you in the Store.

### Steps to reproduce the bug

slept in the car for 2 day straight and then video starts

### Savegame file

[New Amir Save Game.txt](https://github.com/hovgaardgames/bigambitions/files/8391081/New.Amir.Save.Game.txt)

### Screenshots or videos

https://youtu.be/TDrX0BgiHdA

**Comment by Gerwanese** [comment]
This happens when hiring a delivery driver for a store (they're only meant to be used in a warehouse).
We'll need some validation for that.

Savegame for reproduction:
[Tycoon.json.txt](https://github.com/hovgaardgames/bigambitions/files/8391136/Tycoon.json.txt)
1. Call Anderson Recruitment and request delivery drivers for Gifty's
2. Sleep one day in the car to get candidates
3. Try to hire one of the candidates
=> The button won't work, instead you'll end up inside the store and the game is broken.

**Comment by Gerwanese** [comment]
Additional information: A similar bug occurs when you try to assign a driver to a shop in the MyEmployees app (tried to move the existing delivery driver from Warehouse to Gifty's).
So we need a validation there too:
It should only be possible to hire or assign an employee for a business that requires that type of employee

**Comment by Amir1460** [comment]
Maybe hiring a person for the wrong Business should make them Unassigned

**Comment by Amir1460** [comment]
![Big_Ambitions_lFP6yGn1Jm](https://user-images.githubusercontent.com/102742259/161103119-f50109fd-3c1c-476b-8896-7245b88d8a68.gif)
Now shes forever in my game, because i saved after hiring her

**Comment by David-Goru** [comment]
Fixed in build 611
