### ISSUE TITLE
Headquarters: Copying the schedule of Saturday or Sunday to all days makes it closed, can't be opened again

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1018]
### Build number

614

### Bug description

It is possible to copy the headquarters' "schedule" for Saturday or Sunday to all days, effectively closing it on all days. This cannot be undone, unless you shut down the business and start it again.
The option to copy the schedule should not be available for the headquarters.

### Savegame file

[FridgeGlitch.json.txt](https://github.com/hovgaardgames/bigambitions/files/8413325/FridgeGlitch.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/161637115-f6e0a590-ad7a-4b5c-9327-fe560aeae842.mp4

**Comment by David-Goru** [comment]
Fixed in build 709

**Comment by imandings** [comment]
Able to replicate this, any news on when 709 will be available to try? I'm unable to continue with my warehouse due to this - can't reset the hours unless you know a file hack for the savefile?

**Comment by imandings** [comment]
Doesn't accept JSON files, so I've renamed it to json.txt :
[New Andy Save Game.json.txt](https://github.com/hovgaardgames/bigambitions/files/8474878/New.Andy.Save.Game.json.txt)
)

**Comment by David-Goru** [comment]
Warehouse doesn't have a schedule @imandings (thought it was the Headquarters). 

It seems that you're stuck at the "Get 100$ revenue in one day per business", which is also a known bug that will be fixed in the next beta 😅
Right now, that objective only checks for retail businesses. We've reworked how the backend for the tutorial works, so Beta 2 should fix most of the current problems. Sadly we can't launch that into the current Beta 1. 
[New.Andy.Save.Game.json.txt](https://github.com/hovgaardgames/bigambitions/files/8479034/New.Andy.Save.Game.json.txt)

Here's your savegame with the "Get 100$ revenue/business" objective completed:
[New.Andy.Save.Game.json.txt](https://github.com/hovgaardgames/bigambitions/files/8479040/New.Andy.Save.Game.json.txt)

If you find any other problem, don't hesitate to contact us!
