### ISSUE TITLE
Scenery objects not avoided by mouse navigation

### ISSUE THREAD

**Issue by Navsigda** [hovgaardgames/bigambitions#695]
### Build number

245

### Bug description

Traversing a sidewalk from the left to the right of the screen has a large probability to have the character walk around an advertising sign and carry on on his route. Doing the same movement but from the right to the left of the screen causes a collision with the advertising sign and the character's direction changes to directly face the building, catching the character in an infinite walking animation. 

### Steps to reproduce the bug

Head to 13th 3rd Avenue on 2nd Street and use the mouse cursor to walk from the right to the left of the screen, past the hotdog cart and the street sign in front of the building. 

### Screenshots or videos

![Sidewalk traversing](https://user-images.githubusercontent.com/55465313/145111271-eb77d0ac-eeba-4a57-91fd-70b51351d28e.png)

**Comment by Gerwanese** [comment]
I can verify it for this specific building (13 Third Avenue). The reason is that the paved area in front of the building (the yellow area in the screenshot above) can be walked on but at the same time is being considered part of the building (sometimes triggering the outline), which makes the player try to run into the building.

[Build288-HeadVSWall.json.txt](https://github.com/hovgaardgames/bigambitions/files/7707463/Build288-HeadVSWall.json.txt)


https://user-images.githubusercontent.com/17579552/145902381-d9d72407-3fb4-406f-8645-09f6c4023b1a.mp4

**Comment by jokoho48** [comment]
Fixed in Build 294
